// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPDsiT7bzoTLFqt34K8DNOPNZv0jD_l0',
    appId: '1:976200443140:web:889c802644ac8757e65c51',
    messagingSenderId: '976200443140',
    projectId: 'budgetapp-8c88c',
    authDomain: 'budgetapp-8c88c.firebaseapp.com',
    storageBucket: 'budgetapp-8c88c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfH4JUOGtrTVEw5n8WmQOh8nwnaz2ICvw',
    appId: '1:976200443140:android:2db98d6183173e81e65c51',
    messagingSenderId: '976200443140',
    projectId: 'budgetapp-8c88c',
    storageBucket: 'budgetapp-8c88c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzU3zg8wJopRC_OYldUZ13R22pp7U2xF4',
    appId: '1:976200443140:ios:9e209db2041fc175e65c51',
    messagingSenderId: '976200443140',
    projectId: 'budgetapp-8c88c',
    storageBucket: 'budgetapp-8c88c.firebasestorage.app',
    iosBundleId: 'com.example.budgetapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzU3zg8wJopRC_OYldUZ13R22pp7U2xF4',
    appId: '1:976200443140:ios:9e209db2041fc175e65c51',
    messagingSenderId: '976200443140',
    projectId: 'budgetapp-8c88c',
    storageBucket: 'budgetapp-8c88c.firebasestorage.app',
    iosBundleId: 'com.example.budgetapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPDsiT7bzoTLFqt34K8DNOPNZv0jD_l0',
    appId: '1:976200443140:web:d0ba496d91c956eee65c51',
    messagingSenderId: '976200443140',
    projectId: 'budgetapp-8c88c',
    authDomain: 'budgetapp-8c88c.firebaseapp.com',
    storageBucket: 'budgetapp-8c88c.firebasestorage.app',
  );
}
